fmm2d-L4: fmm2d-L4.c fmm2d.h
	gcc -O -o fmm2d-L4 fmm2d-L4.c -lm

fmm2d-L5: fmm2d-L5.c fmm2d-L5.h
	gcc -O -o fmm2d-L5 fmm2d-L5.c -lm

fmm2d-L6: fmm2d-L6.c fmm2d-L6.h
	gcc -O -o fmm2d-L6 fmm2d-L6.c -lm

fmm2d-L7: fmm2d-L7.c fmm2d-L7.h
	gcc -O -o fmm2d-L7 fmm2d-L7.c -lm

fmm2d-flop: fmm2d-flop.c fmm2d-flop.h
	gcc -O -o fmm2d-flop fmm2d-flop.c -lm